DICTIONARY_DATA = [
    # 動詞
    ("tener", "テネール", "不規則動詞 [動]", "① （物・人を）持っている、所有している<br>② （年齢が）〜歳である<br>③ （空腹・眠気・寒さなどの生理的感覚を）感じる<br>④ 【tener que + 不定詞】〜しなければならない（義務）<br>⑤ 【tener ganas de + 不定詞】〜したい（強い欲求）<br>⑥ 【tener razón】正しい、もっともである", "・<b>Tengo un coche nuevo.</b>（私は新しい車を持っています）<br>・<b>¿Cuántos años tienes? - Tengo 20 años.</b>（何歳ですか？ - 20歳です）<br>・<b>Tengo mucha hambre y sed.</b>（とてもお腹が空いて喉が渇いています）<br>・<b>Tengo que estudiar español hoy.</b>（今日はスペイン語を勉強しなければなりません）<br>・<b>Tienes razón.</b>（君の言う通りだ/君が正しい）", "動詞"),
    ("ser", "セール", "不規則動詞 [動]", "① （本質・属性・身元・国籍・職業が）〜である<br>② （時刻・日付が）〜である<br>③ （素材・所有が）〜のものである（de 〜）<br>④ （イベントが）開催される、行われる", "・<b>Yo soy japonés y soy estudiante.</b>（私は日本人で学生です）<br>・<b>Hoy es lunes. Son las tres de la tarde.</b>（今日は月曜日です。午後3時です）<br>・<b>Este reloj es de oro.</b>（この時計は金製です）<br>・<b>La fiesta es en mi casa.</b>（パーティーは私の家で行われます）", "動詞"),
    ("estar", "エスタール", "不規則動詞 [動]", "① （一時的な状態・体調・感情が）〜である<br>② （人・物・場所が）〜にいる、〜にある（所在）<br>③ 【estar + 現在分詞】〜している最中である（現在進行形）<br>④ 【estar de acuerdo】賛成である、同意見である", "・<b>¿Cómo estás? - Estoy muy bien, gracias.</b>（元気？ - とても元気です、ありがとう）<br>・<b>¿Dónde está la estación?</b>（駅はどこにありますか？）<br>・<b>Estoy comiendo paella ahora.</b>（今パエリアを食べているところです）<br>・<b>Estoy de acuerdo contigo.</b>（君の意見に賛成です）", "動詞"),
    ("hacer", "アセール", "不規則動詞 [動]", "① （物・料理などを）作る、製作する<br>② （仕事・宿題・行動を）する、行う<br>③ （天気が）〜である（例: hace calor 暑い, hace frío 寒い）<br>④ 【hace + 時間】〜前（時間の経過）", "・<b>Hago la cena todos los días.</b>（私は毎日夕食を作ります）<br>・<b>¿Qué haces los fines de semana?</b>（週末は何をしていますか？）<br>・<b>Hoy hace muy buen tiempo.</b>（今日はとてもいい天気です）<br>・<b>Llegué hace dos días.</b>（私は2日前に到着しました）", "動詞"),
    ("ir", "イール", "不規則動詞 [動]", "① （場所へ）行く、向かう（a 〜へ）<br>② 【ir a + 不定詞】〜する予定だ、〜するつもりだ（近接未来）<br>③ （物事が）うまくいく、進行する（例: ¿Cómo te va? 調子はどう？）<br>④ 【irse】（その場から）立ち去る、出発する、帰る", "・<b>Voy al supermercado en coche.</b>（車でスーパーに行きます）<br>・<b>Mañana voy a viajar a España.</b>（明日スペインへ旅行する予定です）<br>・<b>Todo va bien.</b>（すべて順調です）<br>・<b>Ya me voy. ¡Hasta mañana!</b>（もう行くね。また明日！）", "動詞"),
    ("poder", "ポデール", "不規則動詞 [動]", "① （能力・状況的に）〜できる、可能である<br>② （許可を求めて）〜してもよい（¿Puedo pasar?）<br>③ （依頼で）〜してくれますか？（¿Puedes ayudarme?）<br>④ 【no poder más】もう限界である、耐えられない", "・<b>Puedo hablar un poco de español.</b>（スペイン語が少し話せます）<br>・<b>¿Puedo pagar con tarjeta?</b>（カードで支払えますか？）<br>・<b>¿Puedes repetir, por favor?</b>（もう一度繰り返してくれますか？）<br>・<b>No puedo más, estoy agotado.</b>（もう限界だ、へとへとです）", "動詞"),
    ("querer", "ケレール", "不規則動詞 [動]", "① （物が）欲しい、望む<br>② （〜することを）欲する、〜したい（querer + 不定詞）<br>③ （人を）愛している、好いている（例: Te quiero 愛してる）", "・<b>Quiero un café solo, por favor.</b>（ブラックコーヒーを1つください）<br>・<b>Quiero aprender español rápido.</b>（早くスペイン語を学びたいです）<br>・<b>Te quiero mucho.</b>（君のことが大好きです/愛しています）", "動詞"),
    ("saber", "サベール", "不規則動詞 [動]", "① （情報・事実・知識を）知っている、分かっている<br>② 【saber + 不定詞】（技術・やり方を心得ていて）〜できる<br>③ （味が）〜の味がする（例: sabe bien 美味しい）", "・<b>No sé la respuesta.</b>（私は答えを知りません）<br>・<b>¿Sabes cocinar comida mexicana?</b>（メキシコ料理を作れますか？）<br>・<b>Este plato sabe muy rico.</b>（この料理はとても美味しい味がします）", "動詞"),
    ("conocer", "コノセール", "不規則動詞 [動]", "① （人・場所・街を）知っている、行ったことがある<br>② （人と）知り合う、初対面で会う（例: Mucho gusto en conocerte）<br>③ （芸術・文化を）よく理解している", "・<b>¿Conoces a María? - Sí, la conozco.</b>（マリアさんを知ってる？ - ええ、知っています）<br>・<b>No conozco Madrid todavía.</b>（私はまだマドリードに行ったことがありません）<br>・<b>Encantado de conocerle.</b>（お会いできて光栄です）", "動詞"),
    ("dar", "ダール", "不規則動詞 [動]", "① （人に物を）与える、あげる、渡す<br>② （授業・パーティーなどを）行う、開催する<br>③ 【dar un paseo】散歩する / 【dar las gracias】感謝する", "・<b>Te doy mi número de teléfono.</b>（君に私の電話番号を教えるよ）<br>・<b>Vamos a dar un paseo por la playa.</b>（ビーチを散歩しましょう）<br>・<b>Le di las gracias por su ayuda.</b>（助けてくれたことに感謝を伝えました）", "動詞"),
    ("decir", "デシール", "不規則動詞 [動]", "① （言葉・意見・事実を）言う、述べる、話す<br>② （人に〜するように）伝える、命令する<br>③ 【es decir】つまり、すなわち / 【¿Cómo se dice...?】〜は何と言いますか？", "・<b>¿Qué dices? No te oigo bien.</b>（何て言ったの？よく聞こえません）<br>・<b>Dime la verdad.</b>（私に本当のことを言って）<br>・<b>¿Cómo se dice esto en español?</b>（これはスペイン語で何と言いますか？）", "動詞"),
    ("ver", "ベエール", "不規則動詞 [動]", "① （視覚で）見る、眺める、見学する<br>② （人に）会う、面会する<br>③ （物事を）理解する、わかる（例: ¡Ya veo! なるほど！）<br>④ 【¡Nos vemos!】また会おう！", "・<b>Veo la televisión por la noche.</b>（夜にテレビを見ます）<br>・<b>Mañana veo a mi médico.</b>（明日お医者さんに診てもらいます）<br>・<b>¡Ya veo lo que quieres decir!</b>（君の言いたいことが分かったよ！）<br>・<b>¡Nos vemos pronto!</b>（また近いうちに会おうね！）", "動詞"),
    ("gustar", "グスタール", "規則動詞 [動]", "① （物・事が人に）好まれる、好きである（間接代名詞 + gusta/gustan）<br>② （食べ物の味が）口に合う、気に入る<br>③ （〜するのが）楽しい、心地よい", "・<b>Me gusta mucho el fútbol.</b>（私はサッカーが大好きです）<br>・<b>¿Te gustan los mariscos?</b>（魚介類は好きですか？）<br>・<b>A ella le gusta bailar salsa.</b>（彼女はサルサを踊るのが好きです）", "動詞"),
    ("pasar", "パサール", "規則動詞 [動]", "① （時・期間を）過ごす、経つ<br>② （場所を）通り過ぎる、通過する<br>③ （出来事が）起こる、生じる（例: ¿Qué pasa? どうしたの？）<br>④ （物を）手渡す（例: Pásame la sal 塩を取って）", "・<b>Paso las vacaciones en España.</b>（スペインで休暇を過ごします）<br>・<b>¿Qué te pasa? ¿Estás bien?</b>（どうしたの？大丈夫？）<br>・<b>Pásame el agua, por favor.</b>（お水を取ってください）", "動詞"),
    ("dejar", "デハール", "規則動詞 [動]", "① （物を場所に）置く、残す、置き忘れる<br>② （習慣・仕事を）やめる（dejar de + 不定詞）<br>③ （人に〜することを）許可する、〜させる（dejar + 不定詞）", "・<b>Dejo las llaves en la mesa.</b>（鍵を机の上に置きます）<br>・<b>Voy a dejar de fumar.</b>（タバコをやめるつもりです）<br>・<b>¡Déjame hablar!</b>（私に話させて！）", "動詞"),

    # 名詞
    ("casa", "カサ", "女性名詞 [女]", "① 家、住宅、住まい、建物<br>② 我が家、家庭、実家<br>③ 会社、商店、事務所（例: casa de cambio 両替商）<br>④ 【en casa】在宅で、家で / 【a casa】家へ（帰宅）", "・<b>Voy a casa después del trabajo.</b>（仕事の後、家に帰ります）<br>・<b>Mi casa tiene un jardín bonito.</b>（私の家には綺麗な庭があります）<br>・<b>¿Estás en casa ahora?</b>（今、家にいる？）", "名詞"),
    ("libro", "リブロ", "男性名詞 [男]", "① 本、書籍、書物<br>② （会計などの）帳簿、台帳<br>③ （劇・オペラなどの）台本、リブレット<br>④ 【libro de texto】教科書", "・<b>Estoy leyendo un libro de historia.</b>（歴史の本を読んでいます）<br>・<b>Este libro es muy útil para estudiar.</b>（この本は勉強するのにとても役に立ちます）<br>・<b>Compré tres libros ayer.</b>（昨日、本を3冊買いました）", "名詞"),
    ("tiempo", "ティエンポ", "男性名詞 [男]", "① 時間、期間、暇（例: No tengo tiempo 時間がない）<br>② 天気、気候（例: Hace buen tiempo いい天気）<br>③ 時代、時節<br>④ 【a tiempo】時間通りに、間に合って", "・<b>No tengo mucho tiempo hoy.</b>（今日はあまり時間がありません）<br>・<b>¿Qué tiempo hace en Tokio?</b>（東京の天気はどうですか？）<br>・<b>Llegamos a tiempo al aeropuerto.</b>（空港に時間通りに到着しました）", "名詞"),
    ("vida", "ビダ", "女性名詞 [女]", "① 命、生命<br>② 人生、生涯、生活、暮らし<br>③ 活力、活気（例: ¡Así es la vida! これが人生さ！）", "・<b>La vida es bella.</b>（人生は素晴らしい）<br>・<b>Lleva una vida muy tranquila en el campo.</b>（田舎でとても穏やかな生活を送っています）<br>・<b>¡Así es la vida!</b>（それが人生というものさ！）", "名詞"),
    ("día", "ディア", "男性名詞 [男 ※語尾-aだが男性]", "① 日、1日、昼間（※男性名詞: el día）<br>② 日付、特定の日（例: día festivo 祝日）<br>③ 【buenos días】おはようございます<br>④ 【todos los días】毎日", "・<b>¡Buenos días! ¿Cómo amaneciste?</b>（おはようございます！）<br>・<b>Estudio español todos los días.</b>（毎日スペイン語を勉強しています）<br>・<b>Hoy es un día especial para mí.</b>（今日は私にとって特別な日です）", "名詞"),
    ("noche", "ノチェ", "女性名詞 [女]", "① 夜、日没後の時間<br>② 【buenas noches】こんばんは、おやすみなさい<br>③ 【esta noche】今夜 / 【anoche】昨夜", "・<b>¡Buenas noches! Que descanses.</b>（おやすみなさい！）<br>・<b>Salgo con mis amigos esta noche.</b>（今夜友達と出かけます）<br>・<b>Anoche dormí ocho horas.</b>（昨夜は8時間眠りました）", "名詞"),
    ("año", "アニョ", "男性名詞 [男]", "① 年、1年（365日）<br>② 年齢、歳（例: Tengo 20 años 20歳です）<br>③ 【el año pasado】去年 / 【el año que viene】来年", "・<b>Tengo treinta años.</b>（私は30歳です）<br>・<b>El año pasado viajé a México.</b>（昨年メキシコへ旅行しました）<br>・<b>¡Feliz Año Nuevo a todos!</b>（あけましておめでとうございます！）", "名詞"),
    ("ciudad", "シウダッ(ド)", "女性名詞 [女]", "① 都市、街、都会、市街地<br>② 全市民、街の人々<br>③ 【centro de la ciudad】市内中心部", "・<b>Tokio es una ciudad enorme y segura.</b>（東京は巨大で安全な都市です）<br>・<b>Me encanta pasear por esta ciudad.</b>（この街を散歩するのが大好きです）<br>・<b>El hotel está en el centro de la ciudad.</b>（ホテルは市の中心部にあります）", "名詞"),
    ("agua", "アグア", "女性名詞 [女 ※単数はel agua]", "① 水、飲料水（※単数は el agua）<br>② 雨、雨水<br>③ 【agua mineral】ミネラルウォーター / 【agua con gas / sin gas】炭酸水 / ノンガス水", "・<b>Un vaso de agua sin gas, por favor.</b>（ガスなしの水をコップ1杯ください）<br>・<b>El agua de este río está muy limpia.</b>（この川の水はとても綺麗です）<br>・<b>Bebo mucha agua todos los días.</b>（毎日たくさんの水を飲みます）", "名詞"),
    ("trabajo", "トラバホ", "男性名詞 [男]", "① 仕事、労働、職業、勤務先<br>② 成果物、作品、論文、レポート<br>③ 【¡Buen trabajo!】お疲れ様！よく頑張ったね", "・<b>Tengo mucho trabajo esta semana.</b>（今週は仕事がたくさんあります）<br>・<b>Mi trabajo está cerca de la estación.</b>（私の職場は駅の近くにあります）<br>・<b>¡Buen trabajo!</b>（お疲れ様でした！）", "名詞"),

    # 形容詞
    ("bueno", "ブエノ", "形容詞 [形]", "① （品質・性能が）良い、優れた（ser bueno）<br>② （人が）親切な、優しい（ser bueno）<br>③ （料理が）美味しい（estar bueno）<br>④ （体調・天気が）良好な（estar bueno / buen tiempo）<br>※男性単数名詞の前では「buen」に短縮されます。", "・<b>Es un buen libro para principiantes.</b>（初心者にとって良い本です）<br>・<b>Él es una persona muy buena.</b>（彼はとても親切で優しい人です）<br>・<b>Esta paella está muy buena.</b>（このパエリアはとても美味しいです）", "形容詞"),
    ("grande", "グランデ", "形容詞 [形]", "① （サイズ・面積が）大きい、広い<br>② （年齢が）大人の、年長の<br>③ （名詞の前で短縮形 gran）偉大な、素晴らしい", "・<b>Vivimos en una casa muy grande.</b>（私たちはとても大きな家に住んでいます）<br>・<b>Cervantes es un gran escritor español.</b>（セルバンテスは偉大なスペインの作家です）<br>・<b>Mis hermanos son más grandes que yo.</b>（兄たちは私より年上です）", "形容詞"),
    ("nuevo", "ヌエボ", "形容詞 [形]", "① （新品の）新しい<br>② （これまでにない）斬新な、新出の<br>③ （別の）新たな（例: un nuevo trabajo）", "・<b>Compré un coche nuevo la semana pasada.</b>（先週新しい車を買いました）<br>・<b>Tengo un nuevo compañero de trabajo.</b>（新しい仕事仲間ができました）<br>・<b>¿Qué hay de nuevo?</b>（何か変わったことはある？）", "形容詞"),

    # 前置詞・副詞
    ("para", "パラ", "前置詞 [前]", "① （目的・用途）〜のために、〜向けの（例: para ti 君のために）<br>② （目的地・方向）〜へ向けて（例: para Madrid）<br>③ （期限・期日）〜までに（例: para mañana 明日までに）", "・<b>Este regalo es para mi madre.</b>（このプレゼントは母へのものです）<br>・<b>El autobús sale para Barcelona.</b>（バスはバルセロナに向けて出発します）<br>・<b>Terminaré el informe para el viernes.</b>（金曜日までにレポートを終わらせます）", "前置詞"),
    ("por", "ポル", "前置詞 [前]", "① （原因・理由）〜のせいで、〜のおかげで（例: por la lluvia）<br>② （手段・媒体）〜によって、〜で（例: por teléfono 電話で）<br>③ （通過・場所）〜を通って（例: por el parque 公園を通って）<br>④ （感謝の対象）〜に対して（例: Gracias por todo）", "・<b>Muchas gracias por tu invitación.</b>（招待してくれて本当にありがとう）<br>・<b>Te llamo por teléfono más tarde.</b>（後で電話するね）<br>・<b>Paseo por el parque todas las mañanas.</b>（毎朝公園を散歩します）", "前置詞"),
    ("ya", "ジャ", "副詞 [副]", "① もう、すでに（過去の完了）（例: Ya comí もう食べた）<br>② 今すぐ、直ちに（例: ¡Ven ya! すぐ来て！）<br>③ 【ya no】もう〜ない（状態の終了）", "・<b>¿Ya terminaste tu tarea? - Sí, ya la terminé.</b>（もう宿題終わった？ - うん、終わったよ）<br>・<b>¡Tenemos que salir ya!</b>（もう今すぐ出かけなきゃ！）<br>・<b>Ya no vivo en esa ciudad.</b>（私はもうその街には住んでいません）", "副詞"),
    ("siempre", "シエンプレ", "副詞 [副]", "① いつも、常に、いつでも（頻度100%）<br>② 永遠に、いつまでも（例: para siempre 永遠に）<br>③ 【como siempre】いつものように、相変わらず", "・<b>Siempre tomo café por la mañana.</b>（朝はいつもコーヒーを飲みます）<br>・<b>Te recordaré para siempre.</b>（君のことを永遠に忘れません）<br>・<b>Llegas tarde, como siempre.</b>（相変わらず遅刻だね）", "副詞")
]
